# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 450956736ad7a739d1d98983c55e2c40dc8b169fc2f1633a9c40787370b9f37a1c72188d2cc29d89c0feed8577b362a5638878e2c0ff69d87e2e5ecf165a6fb2

test:
  secret_key_base: 2b76c083ea4310578efab3080cf2d995b13306972b97e93deab162eade48fd2301a546ac5f8d5ffbf15632ddac4db49ccd70f94df42d8d7fd0b715ce8af93a19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
